name: release

run-name: |-
  ${{ github.event_name == 'workflow_dispatch' && format('Manual release for {0}', github.event.inputs.target_release_tag) || format('Release {0}', github.event.release.tag_name) }}

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: The tag of the release you want to append the artifact to
        type: string
        required: true

env:
  IS_THIS_RELEASE: true

permissions:
  contents: write

jobs:
  show_action_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Show action parameters
        run: |
          cat <<EOF > $GITHUB_STEP_SUMMARY
          ## Action Parameters
          - target_release_tag: \`${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.target_release_tag }}\`
          - build_targets: \`1.21.11, 26.1\`
          EOF

  # ensure the input release tag is valid
  validate_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get github release information
        uses: cardinalby/git-get-release-action@1.2.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.target_release_tag }}

  build:
    uses: ./.github/workflows/_step.build.yml
    needs:
      - validate_release
    with:
      release: true

  upload_release_assets:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: release-artifacts

      - name: Upload jars to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'release' && github.event.release.tag_name || github.event.inputs.target_release_tag }}
          files: release-artifacts/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
